//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.Standards = new HashSet<Standard>();
        }

        [Key]
        [Required]
        [Display(Name = "Code")]
        public string appCode { get; set; }
        [Display(Name = "Environment Name")]
        public string appEnvName { get; set; }
        [Display(Name = "Application Name")]
        public string appName { get; set; }
        [Display(Name = "Phase")]
        public string appPhase { get; set; }
        [Display(Name = "OU")]
        public string appOU { get; set; }
        [Display(Name = "Pool")]
        public string appPool { get; set; }
        [Display(Name = "Point of Contact")]
        public string appPOC { get; set; }
        [Display(Name = "Application Owner")]
        public string appOwner { get; set; }
        [Display(Name = "Snow Team")]
        public string appSnowTeam { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Standard> Standards { get; set; }
    }
}
