//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Drive
    {
        [Key]
        [Display(Name = "Code")]
        public int dCode { get; set; }
        [Display(Name = "Name")]
        public string sName { get; set; }
        [Display(Name = "C Size")]
        public Nullable<int> diskCSize { get; set; }
        [Display(Name = "C Name")]
        public string diskCName { get; set; }
        [Display(Name = "D Size")]
        public Nullable<int> diskDSize { get; set; }
        [Display(Name = "D Name")]
        public string diskDName { get; set; }
        [Display(Name = "E Size")]
        public Nullable<int> diskESize { get; set; }
        [Display(Name = "E Name")]
        public string diskEName { get; set; }
        [Display(Name = "F Size")]
        public Nullable<int> diskFSize { get; set; }
        [Display(Name = "F Name")]
        public string diskFName { get; set; }
        [Display(Name = "K Size")]
        public Nullable<int> diskKSize { get; set; }
        [Display(Name = "K Name")]
        public string diskKName { get; set; }
        [Display(Name = "L Size")]
        public Nullable<int> diskLSize { get; set; }
        [Display(Name = "L Name")]
        public string diskLName { get; set; }
        [Display(Name = "M Size")]
        public Nullable<int> diskMSize { get; set; }
        [Display(Name = "M Name")]
        public string diskMName { get; set; }
        [Display(Name = "P Size")]
        public Nullable<int> diskPSize { get; set; }
        [Display(Name = "P Name")]
        public string diskPName { get; set; }
        [Display(Name = "T Size")]
        public Nullable<int> diskTSize { get; set; }
        [Display(Name = "T Name")]
        public string diskTName { get; set; }
        [Display(Name = "S Size")]
        public Nullable<int> diskSSize { get; set; }
        [Display(Name = "S Name")]
        public string diskSName { get; set; }

        public virtual Standard Standard { get; set; }
    }
}
