//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Drive
    {
        [Key]
        [Display(Name = "Code")]
        public int dCode { get; set; }
        [Display(Name = "Name")]
        public string sName { get; set; }
        [Display(Name = "Disk C Size")]
        public Nullable<int> diskCSize { get; set; }
        [Display(Name = "Disk C Name")]
        public string diskCName { get; set; }
        [Display(Name = "Disk D Size")]
        public Nullable<int> diskDSize { get; set; }
        [Display(Name = "Disk D Name")]
        public string diskDName { get; set; }
        [Display(Name = "Disk E Size")]
        public Nullable<int> diskESize { get; set; }
        [Display(Name = "Disk E Name")]
        public string diskEName { get; set; }
        [Display(Name = "Disk F Size")]
        public Nullable<int> diskFSize { get; set; }
        [Display(Name = "Disk F Name")]
        public string diskFName { get; set; }
        [Display(Name = "Disk K Size")]
        public Nullable<int> diskKSize { get; set; }
        [Display(Name = "Disk K Name")]
        public string diskKName { get; set; }
        [Display(Name = "Disk L Size")]
        public Nullable<int> diskLSize { get; set; }
        [Display(Name = "Disk L Name")]
        public string diskLName { get; set; }
        [Display(Name = "Disk M Size")]
        public Nullable<int> diskMSize { get; set; }
        [Display(Name = "Disk M Name")]
        public string diskMName { get; set; }
        [Display(Name = "Disk P Size")]
        public Nullable<int> diskPSize { get; set; }
        [Display(Name = "Disk P Name")]
        public string diskPName { get; set; }
        [Display(Name = "Disk T Size")]
        public Nullable<int> diskTSize { get; set; }
        [Display(Name = "Disk T Name")]
        public string diskTName { get; set; }
        [Display(Name = "Disk S Size")]
        public Nullable<int> diskSSize { get; set; }
        [Display(Name = "Disk S Name")]
        public string diskSName { get; set; }

        public virtual Standard Standard { get; set; }
    }
}
