//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Standard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Standard()
        {
            this.Drives = new HashSet<Drive>();
        }

        [Key]
        [Display(Name = "Name")]
        public string sName { get; set; }
        [Display(Name = "Code")]
        public string appCode { get; set; }
        [Display(Name = "Type")]
        public string sType { get; set; }
        [Display(Name = "Description")]
        public string sDescription { get; set; }
        [Display(Name = "vCPU")]
        public Nullable<int> sVCPU { get; set; }
        [Display(Name = "RAM")]
        public Nullable<int> sRAM { get; set; }
        [Display(Name = "IP")]
        public string sIP { get; set; }
        [Display(Name = "OS")]
        public string sOS { get; set; }
        [Display(Name = "Size")]
        public string sSize { get; set; }
        [Display(Name = "SQL Version")]
        public string sSQLVers { get; set; }
        [Display(Name = "Notes")]
        public string sNotes { get; set; }

        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drive> Drives { get; set; }
    }
}
